content:
  - name: blog_posts
    label: Blog Posts
    path: src/content/blog
    type: collection

    fields:
      - name: title
        label: Título
        type: string
        required: true

      - name: description
        label: Descripción
        type: text

      

      - name: category
        label: Categoría
        type: select
        options:
          values:
            - Tecnología
            - Mantenimiento
            - Normativas
            - Diseño
            - Noticias

      - name: pubDatetime
        label: Fecha de Publicación
        type: date

      - name: draft
        label: Borrador
        type: boolean
        default: false

      - name: tags
        label: Etiquetas
        type: reference
        options:
          type: string